language: node_js
node_js:
  - "8"
before_install:
  - npm i -g @alicloud/fun -g
install:
  - echo "$ENV" | base64 --decode > .env
  - npm i
script: npm test && npm run build

jobs:
  include:
    - stage: release
      node_js: lts/*
      script: skip
      deploy:
        provider: script
        skip_cleanup: true
        script:
          - fun deploy
        branch:
          on: master
