name: Node CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install, build, and test
      run: |
        npm install
        npm run build --if-present
        npm test
      env:
        CI: true
    - name: Prepare release
      run: |
        mkdir -p release/{{ projectName }}
        cp -r README.md release/{{ projectName }}/README.md
        cp -r package-lock.json release/{{ projectName }}/package-lock.json
        cp -r template.yml release/{{ projectName }}/template.yml
        cp -r webpack.common.js release/{{ projectName }}/webpack.common.js
        cp -r package.json release/{{ projectName }}/package.json
        cp -r test release/{{ projectName }}/test
        cp -r webpack.dev.js release/{{ projectName }}/webpack.dev.js
        cp -r src release/{{ projectName }}/src
        cp -r tsconfig.json release/{{ projectName }}/tsconfig.json
        cp -r webpack.prod.js release/{{ projectName }}/webpack.prod.js
    - name: Deploy
      uses: docker://peaceiris/gh-pages:v2.3.1
      env:
        ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        PUBLISH_BRANCH: gh-pages
        PUBLISH_DIR: ./release
      with:
        emptyCommits: true
